--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.6
-- ~ Flyway V13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_message (
    chat_message_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    content text,
    image_key character varying(255),
    message_type character varying(255) NOT NULL,
    chat_room_id bigint NOT NULL,
    CONSTRAINT chat_message_message_type_check CHECK (((message_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'SYSTEM'::character varying])::text[])))
);


--
-- Name: chat_message_chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_message ALTER COLUMN chat_message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_room (
    chat_room_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    chat_room_type character varying(255) NOT NULL,
    team_id bigint,
    image_key character varying(255),
    room_name character varying(255),
    CONSTRAINT chat_room_chat_room_type_check CHECK (((chat_room_type)::text = ANY ((ARRAY['TEAM'::character varying, 'DIRECT'::character varying, 'GROUP'::character varying])::text[])))
);


--
-- Name: chat_room_chat_room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_room ALTER COLUMN chat_room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_chat_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_room_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_room_member (
    chat_room_mem_ber_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    last_read_message_id bigint,
    chat_room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    visible_from_message_id bigint DEFAULT 0 NOT NULL,
    custom_room_name character varying(255),
    custom_image_key character varying(255)
);


--
-- Name: chat_room_member_chat_room_mem_ber_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_room_member ALTER COLUMN chat_room_mem_ber_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_room_member_chat_room_mem_ber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event (
    event_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    color character varying(255),
    description character varying(255),
    end_at timestamp(6) without time zone,
    is_all_day boolean,
    is_finished boolean,
    is_single boolean,
    sequence integer,
    start_at timestamp(6) without time zone,
    title character varying(255),
    uid character varying(255),
    team_id bigint,
    CONSTRAINT event_color_check CHECK (((color)::text = ANY ((ARRAY['SUN'::character varying, 'BLOSSOM'::character varying, 'OCEAN'::character varying, 'LEAF'::character varying, 'ROSE'::character varying, 'PEACH'::character varying, 'LAVENDER'::character varying, 'MINT'::character varying])::text[])))
);


--
-- Name: event_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_participant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_participant (
    event_participant_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    event_role character varying(255),
    event_id bigint NOT NULL,
    team_member_id bigint NOT NULL,
    CONSTRAINT event_participant_event_role_check CHECK (((event_role)::text = ANY ((ARRAY['HOST'::character varying, 'PARTICIPANT'::character varying])::text[])))
);


--
-- Name: event_participant_event_participant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_participant ALTER COLUMN event_participant_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_participant_event_participant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_reminder_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_reminder_log (
    event_reminder_log_id bigint NOT NULL,
    event_id bigint NOT NULL,
    occurrence_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: event_reminder_log_event_reminder_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_reminder_log ALTER COLUMN event_reminder_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_reminder_log_event_reminder_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fcm_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fcm_token (
    fcm_token_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    device_type character varying(255),
    fcm_token character varying(255)
);


--
-- Name: fcm_token_fcm_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fcm_token ALTER COLUMN fcm_token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fcm_token_fcm_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: info_post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.info_post (
    info_post_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    category character varying(255) NOT NULL,
    content character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT info_post_category_check CHECK (((category)::text = ANY ((ARRAY['CONTEST'::character varying, 'CLUB'::character varying, 'EXTERNAL_ACTIVITY'::character varying, 'INTERN'::character varying, 'CAREER_ADVICE'::character varying, 'CASUAL_TALK'::character varying, 'INFO_SHARING'::character varying])::text[])))
);


--
-- Name: info_post_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.info_post_image (
    info_post_image_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    image_key character varying(255),
    sort_order integer,
    info_post_id bigint NOT NULL
);


--
-- Name: info_post_image_info_post_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.info_post_image ALTER COLUMN info_post_image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.info_post_image_info_post_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: info_post_info_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.info_post ALTER COLUMN info_post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.info_post_info_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: info_post_scrap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.info_post_scrap (
    info_post_scrap_id bigint NOT NULL,
    info_post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: info_post_scrap_info_post_scrap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.info_post_scrap ALTER COLUMN info_post_scrap_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.info_post_scrap_info_post_scrap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inquiry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiry (
    inquiry_id bigint NOT NULL,
    inquirer_id bigint NOT NULL,
    inquirer_name character varying(255) NOT NULL,
    type character varying(20) NOT NULL,
    detail character varying(1000),
    status character varying(20) NOT NULL,
    answer character varying(1000),
    answerer_id bigint,
    answerer_name character varying(255),
    answered_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: inquiry_inquiry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.inquiry_inquiry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: inquiry_inquiry_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.inquiry_inquiry_id_seq OWNED BY public.inquiry.inquiry_id;


--
-- Name: intip_sync_cursor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.intip_sync_cursor (
    id bigint NOT NULL,
    last_processed_notice_id bigint,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    notification_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    content character varying(255),
    is_read boolean NOT NULL,
    redirect_url character varying(255),
    title character varying(255),
    type character varying(255),
    receiver_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['NOTICE'::character varying, 'INVITE'::character varying, 'APPLICATION'::character varying, 'CALENDAR'::character varying, 'CHAT'::character varying])::text[])))
);


--
-- Name: notification_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_option; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_option (
    notification_option_id bigint NOT NULL,
    user_id bigint NOT NULL,
    notice_enabled boolean NOT NULL,
    invite_enabled boolean NOT NULL,
    application_enabled boolean NOT NULL,
    calendar_enabled boolean NOT NULL,
    chat_enabled boolean NOT NULL
);


--
-- Name: notification_option_notification_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_option ALTER COLUMN notification_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_option_notification_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruitment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruitment (
    recruitment_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    category character varying(255),
    current_member_count integer NOT NULL,
    description character varying(255) NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    is_opened boolean NOT NULL,
    target_member_count integer NOT NULL,
    title character varying(255) NOT NULL,
    recruiter_id bigint NOT NULL,
    team_id bigint NOT NULL,
    info_post_id bigint,
    CONSTRAINT recruitment_category_check CHECK (((category)::text = ANY ((ARRAY['CONTEST'::character varying, 'STUDY'::character varying, 'CLUB'::character varying, 'PROJECT'::character varying, 'ETC'::character varying, 'EXTERNAL_ACTIVITY'::character varying, 'INTERN'::character varying])::text[])))
);


--
-- Name: recruitment_application; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruitment_application (
    recruitment_application_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    application_status character varying(255) NOT NULL,
    introduction text NOT NULL,
    responded_at timestamp(6) without time zone,
    recruitment_id bigint NOT NULL,
    CONSTRAINT recruitment_application_application_status_check CHECK (((application_status)::text = ANY ((ARRAY['WAITING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: recruitment_application_recruitment_application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruitment_application ALTER COLUMN recruitment_application_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruitment_application_recruitment_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruitment_recruitment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruitment ALTER COLUMN recruitment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruitment_recruitment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruitment_scrap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruitment_scrap (
    recruitment_scrap_id bigint NOT NULL,
    recruitment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: recruitment_scrap_recruitment_scrap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruitment_scrap ALTER COLUMN recruitment_scrap_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.recruitment_scrap_recruitment_scrap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurrence_exception; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurrence_exception (
    recurrence_exception_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    exception_type character varying(255),
    modified_color character varying(255),
    modified_description character varying(255),
    modified_end_at timestamp(6) without time zone,
    modified_is_all_day boolean,
    modified_start_at timestamp(6) without time zone,
    modified_title character varying(255),
    original_occurrence_at timestamp(6) without time zone,
    event_id bigint NOT NULL,
    modified_is_finished boolean,
    CONSTRAINT recurrence_exception_exception_type_check CHECK (((exception_type)::text = ANY ((ARRAY['CANCELLED'::character varying, 'MODIFIED'::character varying])::text[]))),
    CONSTRAINT recurrence_exception_modified_color_check CHECK (((modified_color)::text = ANY ((ARRAY['SUN'::character varying, 'BLOSSOM'::character varying, 'OCEAN'::character varying, 'LEAF'::character varying, 'ROSE'::character varying, 'PEACH'::character varying, 'LAVENDER'::character varying, 'MINT'::character varying])::text[])))
);


--
-- Name: recurrence_exception_participant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurrence_exception_participant (
    recurrence_exception_participant_id bigint CONSTRAINT recurrence_exception_partic_recurrence_exception_parti_not_null NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    event_role character varying(255),
    recurrence_exception_id bigint CONSTRAINT recurrence_exception_participa_recurrence_exception_id_not_null NOT NULL,
    team_member_id bigint NOT NULL,
    CONSTRAINT recurrence_exception_participant_event_role_check CHECK (((event_role)::text = ANY ((ARRAY['HOST'::character varying, 'PARTICIPANT'::character varying])::text[])))
);


--
-- Name: recurrence_exception_particip_recurrence_exception_particip_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recurrence_exception_participant ALTER COLUMN recurrence_exception_participant_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurrence_exception_particip_recurrence_exception_particip_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurrence_exception_recurrence_exception_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recurrence_exception ALTER COLUMN recurrence_exception_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurrence_exception_recurrence_exception_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurrence_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurrence_rule (
    recurrence_rule_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    by_month_day integer,
    freq character varying(255),
    interval_value integer,
    occurrence_count integer,
    series_start_at timestamp(6) without time zone,
    time_zone character varying(255),
    until_at timestamp(6) without time zone,
    event_id bigint NOT NULL,
    CONSTRAINT recurrence_rule_freq_check CHECK (((freq)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'YEARLY'::character varying])::text[])))
);


--
-- Name: recurrence_rule_by_day; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurrence_rule_by_day (
    recurrence_rule_id bigint NOT NULL,
    by_day character varying(255),
    CONSTRAINT recurrence_rule_by_day_by_day_check CHECK (((by_day)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: recurrence_rule_recurrence_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recurrence_rule ALTER COLUMN recurrence_rule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurrence_rule_recurrence_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    refresh_token character varying(500) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report (
    report_id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    reporter_name character varying(255) NOT NULL,
    target_type character varying(20) NOT NULL,
    target_post_id bigint,
    target_post_title character varying(255),
    target_user_id bigint,
    target_user_name character varying(255),
    reason character varying(20) NOT NULL,
    detail character varying(1000),
    status character varying(20) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: report_handle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_handle (
    report_handle_id bigint NOT NULL,
    report_id bigint NOT NULL,
    handler_id bigint,
    handler_name character varying(255),
    post_action character varying(20),
    post_action_detail character varying(1000),
    user_action character varying(20),
    user_action_duration_days integer,
    user_action_detail character varying(1000),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: report_handle_report_handle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.report_handle_report_handle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: report_handle_report_handle_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.report_handle_report_handle_id_seq OWNED BY public.report_handle.report_handle_id;


--
-- Name: report_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.report_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: report_report_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.report_report_id_seq OWNED BY public.report.report_id;


--
-- Name: team; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team (
    team_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    category character varying(255),
    description character varying(255),
    image_key character varying(255),
    link character varying(255),
    name character varying(255) NOT NULL,
    sns character varying(255),
    CONSTRAINT team_category_check CHECK (((category)::text = ANY ((ARRAY['CONTEST'::character varying, 'STUDY'::character varying, 'CLUB'::character varying, 'PROJECT'::character varying, 'ETC'::character varying, 'EXTERNAL_ACTIVITY'::character varying, 'INTERN'::character varying])::text[])))
);


--
-- Name: team_invitation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_invitation (
    team_invitation_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    invite_status character varying(255) NOT NULL,
    responded_at timestamp(6) without time zone,
    receiver_id bigint NOT NULL,
    team_id bigint NOT NULL,
    CONSTRAINT team_invitation_invite_status_check CHECK (((invite_status)::text = ANY ((ARRAY['WAITING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: team_invitation_team_invitation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_invitation ALTER COLUMN team_invitation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_invitation_team_invitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_member (
    team_member_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    team_role character varying(255) NOT NULL,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT team_member_team_role_check CHECK (((team_role)::text = ANY ((ARRAY['LEADER'::character varying, 'MANAGER'::character varying, 'MEMBER'::character varying])::text[])))
);


--
-- Name: team_member_team_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_member ALTER COLUMN team_member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_member_team_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_notice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_notice (
    team_notice_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    content character varying(255),
    is_pinned boolean,
    title character varying(255) NOT NULL,
    team_id bigint NOT NULL
);


--
-- Name: team_notice_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_notice_image (
    team_notice_image_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    image_key character varying(255),
    sort_order integer,
    team_notice_id bigint NOT NULL
);


--
-- Name: team_notice_image_team_notice_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_notice_image ALTER COLUMN team_notice_image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_notice_image_team_notice_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_notice_read; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_notice_read (
    team_notice_read_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    team_notice_id bigint NOT NULL
);


--
-- Name: team_notice_read_team_notice_read_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_notice_read ALTER COLUMN team_notice_read_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_notice_read_team_notice_read_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_notice_team_notice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_notice ALTER COLUMN team_notice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_notice_team_notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_team_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team ALTER COLUMN team_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    department character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    image_key character varying(255),
    is_school_verified boolean,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    student_number character varying(255),
    username character varying(255) NOT NULL,
    suspended_until timestamp without time zone,
    CONSTRAINT users_department_check CHECK (((department)::text = ANY ((ARRAY['KOREAN_LITERATURE'::character varying, 'FRENCH_LITERATURE'::character varying, 'ENGLISH_LITERATURE'::character varying, 'JAPANESE_LITERATURE'::character varying, 'GERMAN_LITERATURE'::character varying, 'CHINESE_LITERATURE'::character varying, 'MATHEMATICS'::character varying, 'PHYSICS'::character varying, 'CHEMISTRY'::character varying, 'FASHION_INDUSTRY'::character varying, 'MARINE_SCIENCE'::character varying, 'SOCIAL_WELFARE'::character varying, 'MEDIA_COMMUNICATION'::character varying, 'LIBRARY_INFORMATION_SCIENCE'::character varying, 'CREATIVE_HUMAN_RESOURCE_DEVELOPMENT'::character varying, 'PUBLIC_ADMINISTRATION'::character varying, 'POLITICAL_INTERNATIONAL'::character varying, 'ECONOMICS'::character varying, 'INTERNATIONAL_TRADE'::character varying, 'CONSUMER_SCIENCE'::character varying, 'GLOBAL_TRADE_LOGISTICS'::character varying, 'ENERGY_CHEMICAL'::character varying, 'ELECTRICAL'::character varying, 'ELECTRONICS'::character varying, 'INDUSTRIAL_MANAGEMENT'::character varying, 'MATERIALS_SCIENCE'::character varying, 'MECHANICAL'::character varying, 'BIOMEDICAL_ROBOTICS'::character varying, 'SAFETY'::character varying, 'COMPUTER_SCIENCE'::character varying, 'INFORMATION_TELECOMMUNICATION'::character varying, 'EMBEDDED_SYSTEM'::character varying, 'BUSINESS_ADMINISTRATION'::character varying, 'DATA_SCIENCE'::character varying, 'TAX_ACCOUNTING'::character varying, 'TECHNOLOGY_MANAGEMENT'::character varying, 'PAINTING'::character varying, 'DESIGN'::character varying, 'PERFORMING_ARTS'::character varying, 'SPORT_SCIENCE'::character varying, 'HEALTH_KINESIOLOGY'::character varying, 'KOREAN_EDUCATION'::character varying, 'ENGLISH_EDUCATION'::character varying, 'JAPANESE_EDUCATION'::character varying, 'MATHEMATICS_EDUCATION'::character varying, 'PHYSICAL_EDUCATION'::character varying, 'EARLY_CHILDHOOD_EDUCATION'::character varying, 'HISTORY_EDUCATION'::character varying, 'ETHICS_EDUCATION'::character varying, 'URBAN_ADMINISTRATION'::character varying, 'URBAN_ENVIRONMENTAL_ENGINEERING'::character varying, 'URBAN_ENGINEERING'::character varying, 'URBAN_ARCHITECTURE'::character varying, 'URBAN_CONSTRUCTION_ENGINEERING'::character varying, 'BIOLOGICAL_SCIENCES'::character varying, 'BIOENGINEERING'::character varying, 'LIBERAL_ARTS'::character varying, 'INTERNATIONAL_LIBERAL_ARTS'::character varying, 'CONVERGENCE'::character varying, 'ICAS'::character varying, 'IBE'::character varying, 'SLOG'::character varying, 'LAW'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'BANNED'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote (
    vote_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    daily_time_end time(0) without time zone,
    daily_time_start time(0) without time zone,
    description character varying(255),
    is_all_day boolean,
    is_opened boolean,
    slot_unit_minute integer,
    title character varying(255),
    team_id bigint
);


--
-- Name: vote_availability; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote_availability (
    vote_availability_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    vote_participant_id bigint,
    vote_time_slot_id bigint
);


--
-- Name: vote_availability_vote_availability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vote_availability ALTER COLUMN vote_availability_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vote_availability_vote_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vote_date; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote_date (
    vote_date_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    date date,
    vote_id bigint
);


--
-- Name: vote_date_vote_date_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vote_date ALTER COLUMN vote_date_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vote_date_vote_date_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vote_participant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote_participant (
    vote_participant_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    has_completed boolean,
    team_member_id bigint,
    vote_id bigint
);


--
-- Name: vote_participant_vote_participant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vote_participant ALTER COLUMN vote_participant_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vote_participant_vote_participant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vote_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote_result (
    vote_result_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_all_day boolean,
    selected_end_at timestamp(6) without time zone,
    selected_start_at timestamp(6) without time zone,
    event_id bigint,
    vote_id bigint
);


--
-- Name: vote_result_vote_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vote_result ALTER COLUMN vote_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vote_result_vote_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vote_time_slot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vote_time_slot (
    vote_time_slot_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    slot_end_at time(0) without time zone,
    slot_start_at time(0) without time zone,
    vote_date_id bigint
);


--
-- Name: vote_time_slot_vote_time_slot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vote_time_slot ALTER COLUMN vote_time_slot_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vote_time_slot_vote_time_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vote_vote_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vote ALTER COLUMN vote_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vote_vote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inquiry inquiry_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry ALTER COLUMN inquiry_id SET DEFAULT nextval('public.inquiry_inquiry_id_seq'::regclass);


--
-- Name: report report_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report ALTER COLUMN report_id SET DEFAULT nextval('public.report_report_id_seq'::regclass);


--
-- Name: report_handle report_handle_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_handle ALTER COLUMN report_handle_id SET DEFAULT nextval('public.report_handle_report_handle_id_seq'::regclass);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (chat_message_id);


--
-- Name: chat_room_member chat_room_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT chat_room_member_pkey PRIMARY KEY (chat_room_mem_ber_id);


--
-- Name: chat_room chat_room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT chat_room_pkey PRIMARY KEY (chat_room_id);


--
-- Name: event_participant event_participant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participant
    ADD CONSTRAINT event_participant_pkey PRIMARY KEY (event_participant_id);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (event_id);


--
-- Name: event_reminder_log event_reminder_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_reminder_log
    ADD CONSTRAINT event_reminder_log_pkey PRIMARY KEY (event_reminder_log_id);


--
-- Name: fcm_token fcm_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fcm_token
    ADD CONSTRAINT fcm_token_pkey PRIMARY KEY (fcm_token_id);


--
-- Name: info_post_image info_post_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post_image
    ADD CONSTRAINT info_post_image_pkey PRIMARY KEY (info_post_image_id);


--
-- Name: info_post info_post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post
    ADD CONSTRAINT info_post_pkey PRIMARY KEY (info_post_id);


--
-- Name: info_post_scrap info_post_scrap_info_post_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post_scrap
    ADD CONSTRAINT info_post_scrap_info_post_id_user_id_key UNIQUE (info_post_id, user_id);


--
-- Name: info_post_scrap info_post_scrap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post_scrap
    ADD CONSTRAINT info_post_scrap_pkey PRIMARY KEY (info_post_scrap_id);


--
-- Name: inquiry inquiry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiry
    ADD CONSTRAINT inquiry_pkey PRIMARY KEY (inquiry_id);


--
-- Name: intip_sync_cursor intip_sync_cursor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intip_sync_cursor
    ADD CONSTRAINT intip_sync_cursor_pkey PRIMARY KEY (id);


--
-- Name: notification_option notification_option_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_option
    ADD CONSTRAINT notification_option_pkey PRIMARY KEY (notification_option_id);


--
-- Name: notification_option notification_option_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_option
    ADD CONSTRAINT notification_option_user_id_key UNIQUE (user_id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (notification_id);


--
-- Name: recruitment_application recruitment_application_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_application
    ADD CONSTRAINT recruitment_application_pkey PRIMARY KEY (recruitment_application_id);


--
-- Name: recruitment recruitment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment
    ADD CONSTRAINT recruitment_pkey PRIMARY KEY (recruitment_id);


--
-- Name: recruitment_scrap recruitment_scrap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_scrap
    ADD CONSTRAINT recruitment_scrap_pkey PRIMARY KEY (recruitment_scrap_id);


--
-- Name: recruitment_scrap recruitment_scrap_recruitment_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_scrap
    ADD CONSTRAINT recruitment_scrap_recruitment_id_user_id_key UNIQUE (recruitment_id, user_id);


--
-- Name: recurrence_exception_participant recurrence_exception_participant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception_participant
    ADD CONSTRAINT recurrence_exception_participant_pkey PRIMARY KEY (recurrence_exception_participant_id);


--
-- Name: recurrence_exception recurrence_exception_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception
    ADD CONSTRAINT recurrence_exception_pkey PRIMARY KEY (recurrence_exception_id);


--
-- Name: recurrence_rule recurrence_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_rule
    ADD CONSTRAINT recurrence_rule_pkey PRIMARY KEY (recurrence_rule_id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: report_handle report_handle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_handle
    ADD CONSTRAINT report_handle_pkey PRIMARY KEY (report_handle_id);


--
-- Name: report_handle report_handle_report_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_handle
    ADD CONSTRAINT report_handle_report_id_key UNIQUE (report_id);


--
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (report_id);


--
-- Name: team_invitation team_invitation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_invitation
    ADD CONSTRAINT team_invitation_pkey PRIMARY KEY (team_invitation_id);


--
-- Name: team_member team_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_member
    ADD CONSTRAINT team_member_pkey PRIMARY KEY (team_member_id);


--
-- Name: team_notice_image team_notice_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice_image
    ADD CONSTRAINT team_notice_image_pkey PRIMARY KEY (team_notice_image_id);


--
-- Name: team_notice team_notice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice
    ADD CONSTRAINT team_notice_pkey PRIMARY KEY (team_notice_id);


--
-- Name: team_notice_read team_notice_read_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice_read
    ADD CONSTRAINT team_notice_read_pkey PRIMARY KEY (team_notice_read_id);


--
-- Name: team team_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (team_id);


--
-- Name: recurrence_exception uk5co5g3coedmd34yx10e9d2rg6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception
    ADD CONSTRAINT uk5co5g3coedmd34yx10e9d2rg6 UNIQUE (event_id, original_occurrence_at);


--
-- Name: chat_room_member uk5w48j1kpcas1d6bo377vd6vuk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT uk5w48j1kpcas1d6bo377vd6vuk UNIQUE (chat_room_id, user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: vote_result uk839ll78uqie3qhaot2u4lfjhd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_result
    ADD CONSTRAINT uk839ll78uqie3qhaot2u4lfjhd UNIQUE (vote_id);


--
-- Name: recurrence_exception_participant uk9ax0fnpjd6yyt6eeed8xp946h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception_participant
    ADD CONSTRAINT uk9ax0fnpjd6yyt6eeed8xp946h UNIQUE (recurrence_exception_id, team_member_id);


--
-- Name: users uk_users_student_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_student_number UNIQUE (student_number);


--
-- Name: recurrence_rule ukeag8g7n9t9pfn3c9c2x1dopiw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_rule
    ADD CONSTRAINT ukeag8g7n9t9pfn3c9c2x1dopiw UNIQUE (event_id);


--
-- Name: refresh_token ukf95ixxe7pa48ryn1awmh2evt7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukf95ixxe7pa48ryn1awmh2evt7 UNIQUE (user_id);


--
-- Name: team_notice_read ukhkb5d71r4jd981lyxiq6qhq2e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice_read
    ADD CONSTRAINT ukhkb5d71r4jd981lyxiq6qhq2e UNIQUE (team_notice_id, created_by);


--
-- Name: team_member ukj6w13vhqtsr7j4ood3u049ttc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_member
    ADD CONSTRAINT ukj6w13vhqtsr7j4ood3u049ttc UNIQUE (team_id, user_id);


--
-- Name: vote_participant ukj8ki7rb9ihpc2cc7qmyw8mn92; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_participant
    ADD CONSTRAINT ukj8ki7rb9ihpc2cc7qmyw8mn92 UNIQUE (vote_id, team_member_id);


--
-- Name: vote_result ukkv8eegbagrq07s8nvpmmsvee6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_result
    ADD CONSTRAINT ukkv8eegbagrq07s8nvpmmsvee6 UNIQUE (event_id);


--
-- Name: vote_time_slot ukm6sc0gd7f3dfknm40tcks52jp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_time_slot
    ADD CONSTRAINT ukm6sc0gd7f3dfknm40tcks52jp UNIQUE (vote_date_id, slot_start_at, slot_end_at);


--
-- Name: refresh_token ukmpvu2fmreqp9cqddttyfaym9v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukmpvu2fmreqp9cqddttyfaym9v UNIQUE (refresh_token);


--
-- Name: vote_date uknls82a98a69dewpe9d2hh0pjt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_date
    ADD CONSTRAINT uknls82a98a69dewpe9d2hh0pjt UNIQUE (vote_id, date);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: event_participant uks4kj7dphmu25a0a2dt686yhq6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participant
    ADD CONSTRAINT uks4kj7dphmu25a0a2dt686yhq6 UNIQUE (event_id, team_member_id);


--
-- Name: vote_availability ukt7gicf19qgki9ddnhttf4bst2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_availability
    ADD CONSTRAINT ukt7gicf19qgki9ddnhttf4bst2 UNIQUE (vote_participant_id, vote_time_slot_id);


--
-- Name: event_reminder_log uq_event_reminder; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_reminder_log
    ADD CONSTRAINT uq_event_reminder UNIQUE (event_id, occurrence_at);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: vote_availability vote_availability_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_availability
    ADD CONSTRAINT vote_availability_pkey PRIMARY KEY (vote_availability_id);


--
-- Name: vote_date vote_date_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_date
    ADD CONSTRAINT vote_date_pkey PRIMARY KEY (vote_date_id);


--
-- Name: vote_participant vote_participant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_participant
    ADD CONSTRAINT vote_participant_pkey PRIMARY KEY (vote_participant_id);


--
-- Name: vote vote_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT vote_pkey PRIMARY KEY (vote_id);


--
-- Name: vote_result vote_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_result
    ADD CONSTRAINT vote_result_pkey PRIMARY KEY (vote_result_id);


--
-- Name: vote_time_slot vote_time_slot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_time_slot
    ADD CONSTRAINT vote_time_slot_pkey PRIMARY KEY (vote_time_slot_id);


--
-- Name: idx_event_reminder_occurrence_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_reminder_occurrence_at ON public.event_reminder_log USING btree (occurrence_at);


--
-- Name: vote_result fk1q6rqiripu5ukio16qr41sf2a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_result
    ADD CONSTRAINT fk1q6rqiripu5ukio16qr41sf2a FOREIGN KEY (vote_id) REFERENCES public.vote(vote_id);


--
-- Name: event_participant fk34d29116lgmcdnp18145tjpwo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participant
    ADD CONSTRAINT fk34d29116lgmcdnp18145tjpwo FOREIGN KEY (team_member_id) REFERENCES public.team_member(team_member_id);


--
-- Name: vote_availability fk3cj5k0eui9awmv6beitnpgoam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_availability
    ADD CONSTRAINT fk3cj5k0eui9awmv6beitnpgoam FOREIGN KEY (vote_participant_id) REFERENCES public.vote_participant(vote_participant_id);


--
-- Name: recruitment fk4eg9mmpn1e0x7kp3ic35hn3cy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment
    ADD CONSTRAINT fk4eg9mmpn1e0x7kp3ic35hn3cy FOREIGN KEY (recruiter_id) REFERENCES public.users(user_id);


--
-- Name: vote_time_slot fk4wacpy3wo2sxvsyw1cdjf7uce; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_time_slot
    ADD CONSTRAINT fk4wacpy3wo2sxvsyw1cdjf7uce FOREIGN KEY (vote_date_id) REFERENCES public.vote_date(vote_date_id);


--
-- Name: recurrence_exception_participant fk52qporg0a8tgnag57otegr5w3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception_participant
    ADD CONSTRAINT fk52qporg0a8tgnag57otegr5w3 FOREIGN KEY (team_member_id) REFERENCES public.team_member(team_member_id);


--
-- Name: event_participant fk5hxneasi6gucfdlc8690c1ngc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_participant
    ADD CONSTRAINT fk5hxneasi6gucfdlc8690c1ngc FOREIGN KEY (event_id) REFERENCES public.event(event_id);


--
-- Name: vote_date fk5rs3mdfrifyp3ynb8d954jolj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_date
    ADD CONSTRAINT fk5rs3mdfrifyp3ynb8d954jolj FOREIGN KEY (vote_id) REFERENCES public.vote(vote_id);


--
-- Name: recruitment fk7ppvmsval12q2ej837rn2mkcc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment
    ADD CONSTRAINT fk7ppvmsval12q2ej837rn2mkcc FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: recruitment fk8k7vqidkeim6x919d4nnvu2yl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment
    ADD CONSTRAINT fk8k7vqidkeim6x919d4nnvu2yl FOREIGN KEY (info_post_id) REFERENCES public.info_post(info_post_id);


--
-- Name: vote_participant fk8kpboph37dhw4ryk75odb1e3u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_participant
    ADD CONSTRAINT fk8kpboph37dhw4ryk75odb1e3u FOREIGN KEY (team_member_id) REFERENCES public.team_member(team_member_id);


--
-- Name: recurrence_rule_by_day fk8r2a5tyriaq1m5ubkka97wxf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_rule_by_day
    ADD CONSTRAINT fk8r2a5tyriaq1m5ubkka97wxf FOREIGN KEY (recurrence_rule_id) REFERENCES public.recurrence_rule(recurrence_rule_id);


--
-- Name: vote_participant fk8v611tho31tvbplr6k35uu6qt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_participant
    ADD CONSTRAINT fk8v611tho31tvbplr6k35uu6qt FOREIGN KEY (vote_id) REFERENCES public.vote(vote_id);


--
-- Name: team_invitation fk9csio8rq6rs3jq3dk15kmrw3l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_invitation
    ADD CONSTRAINT fk9csio8rq6rs3jq3dk15kmrw3l FOREIGN KEY (receiver_id) REFERENCES public.users(user_id);


--
-- Name: team_member fk9ubp79ei4tv4crd0r9n7u5i6e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_member
    ADD CONSTRAINT fk9ubp79ei4tv4crd0r9n7u5i6e FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: recurrence_exception_participant fka6j468of2aop5xhafbun9hqun; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception_participant
    ADD CONSTRAINT fka6j468of2aop5xhafbun9hqun FOREIGN KEY (recurrence_exception_id) REFERENCES public.recurrence_exception(recurrence_exception_id);


--
-- Name: recurrence_exception fkasncvmomd1fcqwnu6gc0xnkr1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_exception
    ADD CONSTRAINT fkasncvmomd1fcqwnu6gc0xnkr1 FOREIGN KEY (event_id) REFERENCES public.event(event_id);


--
-- Name: info_post_image fkbdvffci7b7r3m0bqrslv7gl7s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post_image
    ADD CONSTRAINT fkbdvffci7b7r3m0bqrslv7gl7s FOREIGN KEY (info_post_id) REFERENCES public.info_post(info_post_id);


--
-- Name: chat_room_member fkcid1ck7111rvw7w8x2hupdkna; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT fkcid1ck7111rvw7w8x2hupdkna FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: vote fkcntcqimwfpy2qk3c6kwscgnop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote
    ADD CONSTRAINT fkcntcqimwfpy2qk3c6kwscgnop FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: team_member fkcwlc6ivvbf5svve5fmbg71vks; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_member
    ADD CONSTRAINT fkcwlc6ivvbf5svve5fmbg71vks FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: notification fkdammjl0v5xfaegi926ugx6254; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkdammjl0v5xfaegi926ugx6254 FOREIGN KEY (receiver_id) REFERENCES public.users(user_id);


--
-- Name: team_notice_image fkf8q2wu7du65m5w2oji198uwr6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice_image
    ADD CONSTRAINT fkf8q2wu7du65m5w2oji198uwr6 FOREIGN KEY (team_notice_id) REFERENCES public.team_notice(team_notice_id);


--
-- Name: team_notice fkfi361uirj4w432epmnfx0v6gt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice
    ADD CONSTRAINT fkfi361uirj4w432epmnfx0v6gt FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: recruitment_application fkialcjvc9dd1nxmw7brapo80hw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_application
    ADD CONSTRAINT fkialcjvc9dd1nxmw7brapo80hw FOREIGN KEY (recruitment_id) REFERENCES public.recruitment(recruitment_id);


--
-- Name: recurrence_rule fkj0mx1pjyqo6iua5an85j27nml; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurrence_rule
    ADD CONSTRAINT fkj0mx1pjyqo6iua5an85j27nml FOREIGN KEY (event_id) REFERENCES public.event(event_id);


--
-- Name: chat_message fkj52yap2xrm9u0721dct0tjor9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fkj52yap2xrm9u0721dct0tjor9 FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(chat_room_id);


--
-- Name: vote_availability fklf03rdb4butdpnhupy81i90hx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_availability
    ADD CONSTRAINT fklf03rdb4butdpnhupy81i90hx FOREIGN KEY (vote_time_slot_id) REFERENCES public.vote_time_slot(vote_time_slot_id);


--
-- Name: team_notice_read fkmdmv3q8qthqpw4pgmom1ofqdv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_notice_read
    ADD CONSTRAINT fkmdmv3q8qthqpw4pgmom1ofqdv FOREIGN KEY (team_notice_id) REFERENCES public.team_notice(team_notice_id);


--
-- Name: vote_result fkn09tafr4ot5q1aka0yksq8sp2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vote_result
    ADD CONSTRAINT fkn09tafr4ot5q1aka0yksq8sp2 FOREIGN KEY (event_id) REFERENCES public.event(event_id);


--
-- Name: chat_room_member fko6a9v51aal2574fjb1ldlw4di; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room_member
    ADD CONSTRAINT fko6a9v51aal2574fjb1ldlw4di FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(chat_room_id);


--
-- Name: event fko7r78aa4ksoidjb2oh13jsgc5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fko7r78aa4ksoidjb2oh13jsgc5 FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: chat_room fksf854myki89xjvyqohhrp4aqd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_room
    ADD CONSTRAINT fksf854myki89xjvyqohhrp4aqd FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: team_invitation fkt1324odwq1822y9yy49qagjg9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_invitation
    ADD CONSTRAINT fkt1324odwq1822y9yy49qagjg9 FOREIGN KEY (team_id) REFERENCES public.team(team_id);


--
-- Name: info_post_scrap info_post_scrap_info_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post_scrap
    ADD CONSTRAINT info_post_scrap_info_post_id_fkey FOREIGN KEY (info_post_id) REFERENCES public.info_post(info_post_id);


--
-- Name: info_post_scrap info_post_scrap_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_post_scrap
    ADD CONSTRAINT info_post_scrap_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: notification_option notification_option_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_option
    ADD CONSTRAINT notification_option_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: recruitment_scrap recruitment_scrap_recruitment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_scrap
    ADD CONSTRAINT recruitment_scrap_recruitment_id_fkey FOREIGN KEY (recruitment_id) REFERENCES public.recruitment(recruitment_id);


--
-- Name: recruitment_scrap recruitment_scrap_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_scrap
    ADD CONSTRAINT recruitment_scrap_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: report_handle report_handle_report_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_handle
    ADD CONSTRAINT report_handle_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.report(report_id);


--
-- PostgreSQL database dump complete
--


