services:
  app:
    container_name: inu-teamflow-prod
    image: ${DOCKER_USERNAME}/inu-teamflow:latest
    ports:
      - "8151:8080"
    volumes:
      - ./logs:/var/log/spring
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      ORACLE_URL: ${ORACLE_URL}
      ORACLE_USERNAME: ${ORACLE_USERNAME}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      CLOUDFRONT_DOMAIN: ${CLOUDFRONT_DOMAIN}
      FCM_PROJECT_ID: ${FCM_PROJECT_ID}
      TZ: ${TZ}
    restart: unless-stopped
