spring:
  config:
    activate:
      on-profile: prod

  application:
    name: inu-teamflow

  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    web:
      pageable:
        max-page-size: 100 # 최대 페이지 크기 100

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

oracle:
  datasource:
    jdbc-url: ${ORACLE_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  enabled: true

jwt:
  secret: ${JWT_SECRET}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  region:
    static: ${AWS_REGION}
  s3:
    bucket: ${S3_BUCKET_NAME}
  cloudfront:
    domain: ${CLOUDFRONT_DOMAIN}

fcm:
  file_path: firebase/inu-teamflow-firebase-adminsdk.json
  project_id: ${FCM_PROJECT_ID}