CREATE TABLE event_reminder_log (
    event_reminder_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT    NOT NULL,
    occurrence_at TIMESTAMP NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT uq_event_reminder UNIQUE (event_id, occurrence_at)
);
CREATE INDEX idx_event_reminder_occurrence_at ON event_reminder_log (occurrence_at);