CREATE TABLE notification_option (
    notification_option_id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT  NOT NULL UNIQUE REFERENCES users(user_id),
    notice_enabled         BOOLEAN NOT NULL,
    invite_enabled         BOOLEAN NOT NULL,
    application_enabled    BOOLEAN NOT NULL,
    calendar_enabled       BOOLEAN NOT NULL,
    chat_enabled           BOOLEAN NOT NULL
);
